### PR TITLE
custom timestamp

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
initial work to allow this change https://github.com/Frezyx/talker/issues/231

- [x] added new time format and enum to pick it
- [x] make the new time format choice available in settings and passed everywhere it should be used
- [ ] maybe add custom time output (where people can make a custom function that takes time and returns string that should be used)
- [x] update tests

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
if the custom time function should be the way to go let me know, 
in that case i think it will be more customizable but keeping both options is better to have an easy choice and a fully custom one

**Comment by Frezyx** [comment]
Hello @abdelaziz-mahdy ! Sorry for the delay 🙏🏻 
This is a very important feature for the library, but I have suggestions for how it could be implemented.
Can we provide TimeFormat or formatting method as generateMessage method named (optional) argument ?

Example of code below:
```dart
  String generateTextMessage({TimeFormat timeFormat = TimeFormat.timeAndSeconds}) {
    return '$<formatted time by method>$displayTitle$message$displayStackTrace';
  }
```

This implementation resolve some issues:

1) Providing TimeFormat for all TalkerData instances is not very clear logic. 
2) We can change the log format during the application's operation, but it won't be applied to all created records in history.
3) TalkerHistory saving in runtime in application memory. This field adding more unused data for heap. 

In this case (providing timeFormat as method arg) we can setup it in TalkerSettings in package initialization one time. 
What you think about that ?

**Comment by abdelaziz-mahdy** [comment]
I like that idea, since changing all of the methods was alot of work and didn't think it will be a clean approach, will check it and let you know

**Comment by abdelaziz-mahdy** [comment]
my only problem is that i dont know how to pass it to settings and use it, right now my changes allow to use any time format since i added the param to the `TalkerData` but the point of passing the time format to it is the main problem for me

**Comment by abdelaziz-mahdy** [comment]
using your idea i think we will have a problem with this 
```
extension TalkerDataInterfaceListExt on List<TalkerData> {
  /// The method allows you to get
  /// full text of logs or history
  String get text {
    final sb = StringBuffer();
    for (final data in this) {
      sb.write('${data.generateTextMessage()}\n');
    }
    return sb.toString();
  }
}

```

where my previous approach didnt have a problem with it

**Comment by abdelaziz-mahdy** [comment]
i think its now ready for a review, let me know what should be added or changed, or if its all good

**Review by Frezyx — COMMENTED** [review]
Everything is great in code implementation 👍🏻 
I will try to make some changes to support backward compatibility.

**Comment by Frezyx** [comment]
Hello @abdelaziz-mahdy !
Thank you for contribution ❤️  
This functionality now available in [4.3.0 package version](https://pub.dev/packages/talker_flutter)

**Pull request merged**
