### PR TITLE
Catch all exceptions

### PR DESCRIPTION
**Pull request by zezo357**
Since i was using catcher and wanted to convert to your package.

i was missing the catching all exceptions part (catching unhandled exceptions accross all the app)

i was able to implement that using catcher as a refrence and following this https://docs.flutter.dev/testing/errors

example of how to use it (all exceptions will be sent as `talker.error("unhandled exception", error, stackTrace);`)
```dart
void main() async {
  final talker = TalkerFlutter.init();
  TalkerAppWrapper(
      talker: talker, ensureInitialized: true, rootWidget: MyApp());
}
```

also this pull request includes the changes i did on the log file path issues [https://github.com/Frezyx/talker/pull/99](https://github.com/Frezyx/talker/pull/99)

hope this gets approved, and thank you for the awesome package

### CODE REVIEW

**Comment by zezo357** [comment]
I can remove the part related to the path of logs that was already merged, if that's a problem


Also if you think something should be done to improve the PR let me know

**Comment by Frezyx** [comment]
Hello @zezo357 ! 
Yes, that would be great. I've already looked at this pr a bit. 
I like what you've come up with. But I want to dive deeper to check everything in detail.

**Comment by zezo357** [comment]
> Hello @zezo357 ! 
> Yes, that would be great. I've already looked at this pr a bit. 
> I like what you've come up with. But I want to dive deeper to check everything in detail.

Yeah take your time and I will resolve the conflict and let you know.

**Comment by zezo357** [comment]
@Frezyx hi, i fixed the conflict
also for references for how i did this pr
https://docs.flutter.dev/testing/errors for catching flutter errors
https://dart.dev/articles/archive/zones#handling-asynchronous-errors for catching dart errors

**Comment by zezo357** [comment]
> Hello @zezo357 ! Sorry for a long time waiting.
> I think a lot about your improvements.
> 
> In many projects, there is also another setup code inside the initialization in main method, 
> and not so many people will need the code as in your example.
> 
> But I have a suggestion: we can add this code in example folder. 
> Like full setup talker usage. 
> 
> What you think about it ?

I felt that if we provide the main class it will be easier for developers


Instead of giving them a complicated example? 


Or is it the idea of leaving them to handle each error?

**Comment by Frezyx** [comment]
It's more about to let the developer choose the level of error handling in the application.

**Comment by Frezyx** [comment]
It would be great if there was some other way to initialize Talker for handling all app errors.

**Comment by zezo357** [comment]
> It's more about to let a developer choose the level of error handling in the application.

The objective of the pr is to include the wrapper in the package, if people want to use it (to help them not implement it by themselves)


If they don't want they can run the app without it.



It's just a wrapper for catching up handled exceptions.

**Comment by zezo357** [comment]
> It would be great if there was some other way to initialize Talker for handling all app errors.

From my research I found out the only one is wrapping the run app 

If you found a better way, I would love to use it 😅

**Comment by Frezyx** [comment]
Hello @zezo357 ! 
Can we make method **runTalkerZonedGuarded** instead of ** TalkerAppWrapper** 

I want to be able to configure all initialization methods independently, as done when using **runZonedGuard**
The method should make it possible to forward a callback to which the runApp will be passed.

This way we will be able to initialize all the abundance of methods that you have described and keep the customizability

**Comment by zezo357** [comment]
> Hello @zezo357 ! 
> Can we make method **runTalkerZonedGuarded** instead of **TalkerAppWrapper** 
> 
> I want to be able to configure all initialization methods independently, as done when using **runZonedGuard**
> The method should make it possible to forward a callback to which the runApp will be passed.
> 
> This way we will be able to initialize all the abundance of methods that you have described and keep the customizability

So you want to be a wrapper for runZonedGuard with same parameters and calls it inside it , right? 

If yes I will work on it this weekend, hopefully

**Comment by Frezyx** [comment]
> > Hello @zezo357 !
> > Can we make method **runTalkerZonedGuarded** instead of **TalkerAppWrapper**
> > I want to be able to configure all initialization methods independently, as done when using **runZonedGuard**
> > The method should make it possible to forward a callback to which the runApp will be passed.
> > This way we will be able to initialize all the abundance of methods that you have described and keep the customizability
> 
> So you want to be a wrapper for runZonedGuard with same parameters and calls it inside it , right?
> 
> If yes I will work on it this weekend, hopefully

Yes! You got me right. 
That would be great if I could manage to do that.

**Comment by zezo357** [comment]
i hope i implemented it like how you thought of it

**Review by Frezyx — APPROVED** [review]

**Comment by Frezyx** [comment]
@zezo357 Great! 
That's exactly what I thought. 

But last one. Can you move this code in utils folder ?
Because currently this code is more about tools than about ui.

**Comment by zezo357** [comment]
> @zezo357 Great! 
> That's exactly what I thought. 
> 
> But last one. Can you move this code in utils folder ?
> Because currently this code is more about tools than about ui.

Will do when I Finish work, should I mention you when I do?

**Comment by Frezyx** [comment]
> > @zezo357 Great!
> > That's exactly what I thought.
> > But last one. Can you move this code in utils folder ?
> > Because currently this code is more about tools than about ui.
> 
> Will do when I Finish work, should I mention you when I do?

I’m here today and ready for merge your feature. Also if you make changes later I will merge it. So up for you when you think about make changes 🤝

**Comment by zezo357** [comment]
> @zezo357 Great! That's exactly what I thought.
> 
> But last one. Can you move this code in utils folder ? Because currently this code is more about tools than about ui.

just to be sure you meant a utils folder in flutter_talker right? since this catches flutter exceptions too, so it shouldn't be in talker/utils

also i would like to add an option to catch flutter exception or not , to let the developers choose what they like

**Comment by zezo357** [comment]
> > @zezo357 Great! That's exactly what I thought.
> > But last one. Can you move this code in utils folder ? Because currently this code is more about tools than about ui.
> 
> just to be sure you meant a utils folder in flutter_talker right? since this catches flutter exceptions too, so it shouldn't be in talker/utils
> 
> also i would like to add an option to catch flutter exception or not , to let the developers choose what they like

i did those changes, let me know if you got a better idea.

**Review by Frezyx — APPROVED** [review]

**Comment by Frezyx** [comment]
@zezo357 Thanks a lot! 
You did a great job 🚀

**Pull request merged**
