### PR TITLE
Support web platform downloading logs

### PR DESCRIPTION
**Pull request by Kabak-Siarhei**
### Thanks a lot for contributing!<br>
Provide a description of your changes below

- add support web platform download file logs
- up version sdk

### CODE REVIEW

**Review by Frezyx — CHANGES_REQUESTED** [review]
Hello @Kabak-Siarhei !
Thank you a lot for this great contribution. 

Bu we have one issue with this code. 
**dart:html** can't be used in mobile and desktop platforms.

**Comment by Frezyx** [comment]
In this case we can make importing function with different implementations in separated files

**Comment by Frezyx** [comment]
> In this case we can make importing function with different implementations in separated files

Like this one:
https://stackoverflow.com/questions/59870357/how-to-remove-hash-from-url-in-flutter-web

image

**Comment by Kabak-Siarhei** [comment]
> In this case we can make importing function with different implementations in separated files

Ok. Refactored code.

**Comment by Frezyx** [comment]
@Kabak-Siarhei 
Thank you for contribution 🚀

**Review by Frezyx — APPROVED** [review]

**Pull request merged**
