### PR TITLE
fix TalkerScreen does not respect configured LogLevel setting #168

### PR DESCRIPTION
**Pull request by mylukin**
I solved this issue #168

### CODE REVIEW

**Comment by Frezyx** [comment]
@mylukin hello! Thank you for this PR 👍🏻 
Please remove last commit. If you want to implement LogLevel for talker_bloc_logger settings - create separated Pull Request

**Review by Frezyx — CHANGES_REQUESTED** [review]
@mylukin hello! Thank you for this PR 👍🏻
Please remove last commit. If you want to implement LogLevel for TalkerDioLoggerSettings - create separated Pull Request

**Comment by mylukin** [comment]
ok, I removed last commit. 
thank you!

**Review by Frezyx — APPROVED** [review]

**Comment by Frezyx** [comment]
@mylukin Everything is good and we ready to merge. 
But filter getter in TalkerLogger must be covered by tests before we merge this PR 

[Codecov link](https://app.codecov.io/gh/Frezyx/talker/pull/300/blob/packages/talker_logger/lib/src/logger.dart#:~:text=LoggerFilter%20get%20filter%20%3D%3E%20_filter%3B)

**Pull request merged**
